export const moduleMeta = {
  dashboard: { label: "Dashboard", path: "/" },
  users: { label: "Users", path: "/admin/users" },
  role_groups: { label: "Role Groups", path: "/admin/role-groups" },
  integrations: { label: "Integrations", path: "/admin/integrations" },
  client_billing: { label: "Client Billing", path: "/admin/client-billing" },
  admin_columns: { label: "Admin Columns", path: "/admin/admin-columns" },
  request_access: { label: "Request Access", path: "/request-access" },
  clients: { label: "Clients", path: "/ats/clients" },
  contacts: { label: "Contacts", path: "/ats/contacts" },
  jobs: { label: "Jobs", path: "/ats/jobs" },
  candidates: { label: "Candidates", path: "/ats/candidates" },
  submissions: { label: "Submissions", path: "/ats/submissions" },
  interviews: { label: "Interviews", path: "/ats/interviews" },
  placements: { label: "Placements", path: "/ats/placements" },
  timesheets: { label: "Timesheets", path: "/workforce/timesheets" },
  expenses: { label: "Expenses", path: "/workforce/expenses" },
  contracts: { label: "Contracts", path: "/workforce/contracts" },
  onboarding: { label: "Onboarding", path: "/workforce/onboarding" },
  payroll: { label: "Payroll", path: "/workforce/payroll" },
  documents: { label: "Documents", path: "/documents" },
  resume_parser: { label: "Resume Parser", path: "/documents/resume-parser" },
};
