export const MODULES = {
  dashboard: "dashboard",
  crm: "crm",
  contacts: "contacts",
  jobs: "jobs",
  candidates: "candidates",
  submissions: "submissions",
  placements: "placements",
  workforce: "workforce",
  contracts: "contracts",
  expenses: "expenses",
  onboarding: "onboarding",
  payroll: "payroll",
  timesheets: "timesheets",
  admin: "admin",
  users: "users",
  integrations: "integrations",
  audit_logs: "audit_logs",
  ai: "ai",
};
